name: budgetapp
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment: 
  sdk: '>=2.17.6 <3.0.0'
dependencies: 
  flutter: 
    sdk: flutter
  cupertino_icons: ^1.0.2
  auto_size_text: 3.0.0
  flutter_svg: ^1.0.3
dev_dependencies: 
  flutter_test: 
    sdk: flutter
  flutter_lints: ^2.0.0
flutter: 
  uses-material-design: true
  assets: 
    - packages/budgetapp/assets/images/group.svg
    - packages/budgetapp/assets/images/iconssystemstatusbarwifi.svg
    - packages/budgetapp/assets/images/iconssystemstatusbarsignal.svg
    - packages/budgetapp/assets/images/iconssystemstatusbarlocation.svg
    - packages/budgetapp/assets/images/bgdark.svg
    - packages/budgetapp/assets/images/basemapimage.png
    - packages/budgetapp/assets/images/vuesaxboldlocation.svg
    - packages/budgetapp/assets/images/vuesaxboldtickcircle.svg
    - packages/budgetapp/assets/images/vector.svg
    - packages/budgetapp/assets/images/homeindicatordark.svg
    - packages/budgetapp/assets/images/frame.svg
    - packages/budgetapp/assets/images/line11.svg
    - packages/budgetapp/assets/images/delete.png
    - packages/budgetapp/assets/images/keybackground.svg
    - packages/budgetapp/assets/images/homeindicatorlight.svg
    - packages/budgetapp/assets/images/arrowsquaredown.svg
    - packages/budgetapp/assets/images/arrowsquareup.svg
    - packages/budgetapp/assets/images/ellipse4.png
    - packages/budgetapp/assets/images/ellipse5.png
    - packages/budgetapp/assets/images/ellipse2.png
    - packages/budgetapp/assets/images/gaspump1.png
    - packages/budgetapp/assets/images/rectangle24.png
    - packages/budgetapp/assets/images/ellipse6.png
    - packages/budgetapp/assets/images/money3.svg
    - packages/budgetapp/assets/images/elementequal.svg
    - packages/budgetapp/assets/images/receipttext.svg
    - packages/budgetapp/assets/images/cardadd.svg
    - packages/budgetapp/assets/images/setting2.svg
    - packages/budgetapp/assets/images/ellipse53.png
    - packages/budgetapp/assets/images/image2.png
    - packages/budgetapp/assets/images/rectangle.svg
    - packages/budgetapp/assets/images/deletebutton.png
    - packages/budgetapp/assets/images/shift.svg
    - packages/budgetapp/assets/images/scanbarcode.svg
    - packages/budgetapp/assets/images/line12.svg
    - packages/budgetapp/assets/images/walletadd.svg
    - packages/budgetapp/assets/images/cardtick.svg
    - packages/budgetapp/assets/images/vector6.svg
    - packages/budgetapp/assets/images/vector5.svg
    - packages/budgetapp/assets/images/vector4.svg
    - packages/budgetapp/assets/images/vector3.svg
    - packages/budgetapp/assets/images/vector7.svg
    - packages/budgetapp/assets/images/tag2.svg
    - packages/budgetapp/assets/images/ticketstar.svg
    - packages/budgetapp/assets/images/dollarcircle.svg
    - packages/budgetapp/assets/images/coin.svg
    - packages/budgetapp/assets/images/airplane.svg
    - packages/budgetapp/assets/images/car.svg
    - packages/budgetapp/assets/images/box.svg
    - packages/budgetapp/assets/images/3dcubescan.svg
    - packages/budgetapp/assets/images/vector9.svg
    - packages/budgetapp/assets/images/vector8.svg
    - packages/budgetapp/assets/images/boxadd.svg
    - packages/budgetapp/assets/images/note2.svg
    - packages/budgetapp/assets/images/teacher.svg
    - packages/budgetapp/assets/images/gift.svg
    - packages/budgetapp/assets/images/calculator.svg
    - packages/budgetapp/assets/images/brifecasetimer.svg
    - packages/budgetapp/assets/images/vector2.svg
    - packages/budgetapp/assets/images/ship.svg
    - packages/budgetapp/assets/images/trucktick.svg
    - packages/budgetapp/assets/images/cake.svg
    - packages/budgetapp/assets/images/milk.svg
    - packages/budgetapp/assets/images/batteryfull.svg
    - packages/budgetapp/assets/images/home.svg
    - packages/budgetapp/assets/images/reserve.svg
    - packages/budgetapp/assets/images/coffee.svg
    - packages/budgetapp/assets/images/rectangle.png
    - packages/budgetapp/assets/images/vectorstroke.svg
    - packages/budgetapp/assets/images/bagtick2.svg
    - packages/budgetapp/assets/images/convertcard.svg
    - packages/budgetapp/assets/images/moneychange.svg
    - packages/budgetapp/assets/images/emptywalletadd.svg
    - packages/budgetapp/assets/images/searchnormal.svg
    - packages/budgetapp/assets/images/setting4.svg
    - packages/budgetapp/assets/images/addcircle.svg
    - packages/budgetapp/assets/images/import.svg
    - packages/budgetapp/assets/images/closecircle.svg
    - packages/budgetapp/assets/images/calendar.svg
    - packages/budgetapp/assets/images/bank.svg
    - packages/budgetapp/assets/images/card.svg
    - packages/budgetapp/assets/images/line7.svg
    - packages/budgetapp/assets/images/line8.svg
    - packages/budgetapp/assets/images/line9.svg
    - packages/budgetapp/assets/images/vuesaxlineardocumentcopy.svg
    - packages/budgetapp/assets/images/arrowright.svg
    - packages/budgetapp/assets/images/add.svg
    - packages/budgetapp/assets/images/ellipse54.png
    - packages/budgetapp/assets/images/ellipse55.png
    - packages/budgetapp/assets/images/vuesaxboldeye.svg
    - packages/budgetapp/assets/images/avatar12.png
    - packages/budgetapp/assets/images/ellipse56.png
    - packages/budgetapp/assets/images/ellipse57.png
    - packages/budgetapp/assets/images/edit2.svg
    - packages/budgetapp/assets/images/profilecircle.svg
    - packages/budgetapp/assets/images/link.svg
    - packages/budgetapp/assets/images/clipboardtext.svg
    - packages/budgetapp/assets/images/export.svg
    - packages/budgetapp/assets/images/logout.svg
    - packages/budgetapp/assets/images/infocircle.svg
    - packages/budgetapp/assets/images/avatar.png
    - packages/budgetapp/assets/images/strongbox2.svg
    - packages/budgetapp/assets/images/ellipse1.png
    - packages/budgetapp/assets/images/ellipse3.png
    - packages/budgetapp/assets/images/arrowleft.svg
    - packages/budgetapp/assets/images/gridgraph.svg
    - packages/budgetapp/assets/images/union.png
    - packages/budgetapp/assets/images/arrowdown.svg
    - packages/budgetapp/assets/images/notificationbing.svg
    - packages/budgetapp/assets/images/wallet.svg
    - packages/budgetapp/assets/images/money.svg
    - packages/budgetapp/assets/images/line6.svg
    - packages/budgetapp/assets/images/group73.svg
    - packages/budgetapp/assets/images/walletwithcash.png
    - packages/budgetapp/assets/images/line10.svg
    - packages/budgetapp/assets/images/ellipse58.png
    - packages/budgetapp/assets/images/send.svg
    - packages/budgetapp/assets/images/lock.svg
    - packages/budgetapp/assets/images/cardslash.svg
    - packages/budgetapp/assets/images/information.svg
    - packages/budgetapp/assets/images/cardsend.svg
    - packages/budgetapp/assets/images/cardremove.svg
    - packages/budgetapp/assets/images/weight.svg
    - packages/budgetapp/assets/images/eyeslash.svg
    - packages/budgetapp/assets/images/image3.png
    - packages/budgetapp/assets/images/ellipse59.png
    - packages/budgetapp/assets/images/ellipse60.png
    - packages/budgetapp/assets/images/ellipse61.png
    - packages/budgetapp/assets/images/image4.png
    - packages/budgetapp/assets/images/edit.svg
